<?php
	require_once("includes/dbconfig.php");
	require_once("php/functions.php");
	require_once("php/AddressStruct.class.php");
	require_once("php/AbstractBase.class.php");
	require_once("php/User.class.php");	
	require_once("php/Category.class.php");
	require_once("php/MediaItem.class.php");
	require_once("php/Item.class.php");
	require_once("php/Bid.class.php");
	require_once("php/Listing.class.php");
	require_once("php/OrderTransaction.class.php");
	require_once("php/Session.class.php");
?>